# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

global:
  rabbitmq:
    host:
      value: ""
    username:
      value: guest
    password:
      value: guest
  keycloak:
    url: "" 
    name: keycloak
    service:
      type: http
      port: 80
    realm: ""
    resource: ""
  gateway:
    host: "" 

db:
  uri:
  username:
  password:
  driver:
  platform:
  generateDdl: "false"
  ddlAuto: "none"

postgres:
  enabled: true # should be enabled by default for application chart
  name: postgres
  port: 5432
  username: postgres
  password:
  generateDdl: "false" # default to disable generating Ddl schema
  ddlAuto: "none" # default to disable ddl update

javaOpts:
  xmx: 2048m
  xms: 512m
  other: -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90

## Allows the specification of additional environment variables
extraEnv: |
  # - name: ACT_KEYCLOAK_URL
  #   valueFrom:
  #     configMapKeyRef:
  #       name: {{ .Release.Name }}-keycloak-http
  #       key: expose-keycloak-service-key

# only set this variable if a private registry secret is needed to pull the image
#registryPullSecrets: private-registry-secret
image:
  repository: activiti/activiti-cloud-notifications-graphql
  tag: 7.0.0.SR1
  pullPolicy: IfNotPresent
  
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "false"
    
resources:
  limits:
    memory: 2048Mi
  requests:
    cpu: 500m # more cpu is better for notifications
    memory: 768Mi
probePath: '{{ include "common.ingress-path" . }}/actuator/health'
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 4
  successThreshold: 1
  failureThreshold: 4
readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 15
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 4
terminationGracePeriodSeconds: 20

ingress:
  ## Set to true to enable ingress record generation
  enabled: true
  path: /notifications # configure base path template for ingress, i.e. /{{ .Release.Name }}/notifications
  tls: # true | false 
  tlsSecret: # secret name of the gateway host, tls-activiti-cloud-gateway
  hostName: # override .Values.global.gateway.host
  actuator: 
    enabled: true
    path: /actuator
  graphiql: 
    enabled: true
    path: /graphiql
  web:
    enabled: true
    path: /graphql
  ws: 
    enabled: true
    path: /ws/graphql
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET,PUT,POST,DELETE,PATCH,OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"   
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers 'Access-Control-Allow-Origin: $http_origin';
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: "activiti-cloud-notifications-graphql-route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "md5"
    nginx.ingress.kubernetes.io/session-cookie-path: '{{ include "common.ingress-path" . }}'
    
