apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
        release: {{ .Release.Name }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
{{- if include "common.registry-pull-secrets" . }}
      imagePullSecrets:
      {{- include "common.registry-pull-secrets" . | indent 6 }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "common.container-image" . | quote }}
        imagePullPolicy: {{ include "common.container-image-pull-policy" . }}
        env:
        - name: JAVA_OPTS
          value: "-Xmx{{ .Values.javaOpts.xmx }} -Xms{{ .Values.javaOpts.xms }} {{ .Values.javaOpts.other}}"
        - name: SPRING_APPLICATION_NAME
{{- if .Values.service.name }}
          value: "{{ .Values.service.name }}"
{{- else }}
          value: {{ template "fullname" . }}
{{- end }}
        - name: SPRING_RABBITMQ_HOST
        {{- if .Values.global.rabbitmq.host.value }}
          value: {{ .Values.global.rabbitmq.host.value | quote }}
        {{- else }}
          value: "{{ .Release.Name }}-rabbitmq"
        {{- end }}
        - name: SPRING_RABBITMQ_USERNAME
          value: {{ .Values.global.rabbitmq.username.value }}
        - name: SPRING_RABBITMQ_PASSWORD
          value: {{ .Values.global.rabbitmq.password.value }}
        {{- if include "common.keycloak-url" $ }}
        - name: ACT_KEYCLOAK_URL
          value: {{ include "common.keycloak-url" $ | quote }}
        {{- end }}
        {{- if include "common.keycloak-realm" . }}
        - name: ACT_KEYCLOAK_REALM
          value: {{ include "common.keycloak-realm" . | quote }}
        {{- end }}
        {{- if include "common.keycloak-resource" . }}
        - name: ACT_KEYCLOAK_RESOURCE
          value: {{ include "common.keycloak-resource" . | quote }}
        {{- end }}
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        - name: ACTIVITI_CLOUD_SERVICES_METADATA_EUREKA_STATIC_ENABLED
          value: "false"
        - name: ACTIVITI_CLOUD_SERVICES_METADATA_EUREKA_DYNAMIC_ENABLED
          value: "false"
        - name: ACT_CLOUD_CONFIG_SERVER_ENABLED
          value: "false"
{{ include "common.extra-env" . | indent 8 }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: {{ tpl .Values.probePath . }}
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ tpl .Values.probePath . }}
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}    
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if .Values.extraVolumeMounts }}
        volumeMounts:
{{- with .Values.extraVolumeMounts }}
{{ tpl . $ | indent 10 }}
{{- end }}
{{- end }}
{{- if .Values.extraVolumes }}
      volumes:
{{- with .Values.extraVolumes }}
{{ tpl . $ | indent 8 }}
{{- end }}
{{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
{{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.service.name }}
{{- end }}
