# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
global:
  rabbitmq:
    host:
      value: ""
    username:
      value: guest
    password:
      value: guest
  keycloak:
    url: ""
    name: keycloak
    realm: activiti
    client: activiti
    service:
      type: http
      port: 80
  gateway:
    host: ""

service:
  name: activiti-cloud-modeling
  type: ClusterIP
  backend:
    externalPort: 80
    internalPort: 8080
  frontend:
    externalPort: 80
    internalPort: 80
  annotations:
    fabric8.io/expose: "false"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"


frontend:
#if behind gateway or ingress should be gw path
  basepath: "activiti-cloud-modeling"
  image:
    repository: activiti/activiti-modeling-app
    tag: 7.0.0.Beta3
    pullPolicy: Always
  resources:
    limits:
      memory: 384Mi
    requests:
      cpu: 200m
      memory: 256Mi
  probePath: /
  livenessProbe:
    initialDelaySeconds: 140
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 4
  readinessProbe:
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 3

backend:
  # if not using gateway then external host and http method to reach backend here
  url: ""
  prefix: "activiti-cloud-modeling-backend"
  javaOpts:
    xmx: 512m
    xms: 512m
    other: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
  image:
    repository: activiti/activiti-cloud-modeling
    tag: 7.0.0.Beta3
    pullPolicy: Always
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: 400m
      memory: 512Mi
  probePath: /actuator/health
  livenessProbe:
    initialDelaySeconds: 140
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 4
  readinessProbe:
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 3

terminationGracePeriodSeconds: 20

ingress:
  enabled: false

  backend:
    path: /activiti-cloud-modeling-backend

#  hostName: "activiti-cloud-modeling.REPLACEME"
#  annotations:
#    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/rewrite-target: /
#    nginx.ingress.kubernetes.io/enable-cors: true
#    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
#    nginx.ingress.kubernetes.io/x-forwarded-prefix: true

  ## Set to true to enable websockets
  ws:
    enabled: false

  frontend:
    path: /activiti-cloud-modeling

  ## Set this to true in order to enable TLS on the ingress record
  tls: false

  ## If TLS is set to true, you must declare what secret will store the key/certificate for TLS
  tlsSecret: myTlsSecret
